# Generated by Django 3.0.6 on 2020-05-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=50)),
                ('l_name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=5)),
                ('title', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('office_number', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('corporate_ph', models.CharField(max_length=10)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=10)),
                ('emp_count', models.IntegerField()),
                ('yearly_revenue', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_date', models.DateField()),
                ('activity', models.CharField(max_length=100)),
                ('notes_text', models.CharField(max_length=500)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
    ]
